version: "3"
services:
  cassandra-db:
    image: cassandra
  networks:
    - network-db
  deploy:
    mode: replicated
    replicas: 3
  ports:
    - 7000
  volumes:
    - "~/etl-nosql/db/volumes/cassandra:/var/lib/cassandra"
	
networks:
  networks:
    - cassandra