version: '3.3'
services:
  cassandra-1:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n1
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-1
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/cassandra.yaml"
        target: "/etc/cassandra/cassandra.yaml"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    ports:
      - "7000:7000"
      - "9042:9042"
    networks:
      - cassandra

  cassandra-2:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n2
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-2
      CASSANDRA_SEEDS: "tasks.cassandra-1"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/cassandra.yaml"
        target: "/etc/cassandra/cassandra.yaml"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra
  cassandra-3:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n3
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-3
      CASSANDRA_SEEDS: "tasks.cassandra-1, tasks.cassandra-2"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/cassandra.yaml"
        target: "/etc/cassandra/cassandra.yaml"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra

  cassandra-4:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n4
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-4
      CASSANDRA_SEEDS: "tasks.cassandra-1, tasks.cassandra-2, tasks.cassandra-3"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/cassandra.yaml"
        target: "/etc/cassandra/cassandra.yaml"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra

  cassandra-5:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n5
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-5
      CASSANDRA_SEEDS: "tasks.cassandra-1, tasks.cassandra-2, tasks.cassandra-3, tasks.cassandra-4"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/cassandra.yaml"
        target: "/etc/cassandra/cassandra.yaml"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra

  cassandra-6:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n6
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-6
      CASSANDRA_SEEDS: "tasks.cassandra-1, tasks.cassandra-2, tasks.cassandra-3, tasks.cassandra-4, tasks.cassandra-5"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/cassandra.yaml"
        target: "/etc/cassandra/cassandra.yaml"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra

  cassandra-7:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n7
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-7
      CASSANDRA_SEEDS: "tasks.cassandra-1, tasks.cassandra-2, tasks.cassandra-3, tasks.cassandra-4, tasks.cassandra-5, tasks.cassandra-6"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/cassandra.yaml"
        target: "/etc/cassandra/cassandra.yaml"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra

  cassandra-8:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n8
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-8
      CASSANDRA_SEEDS: "tasks.cassandra-1, tasks.cassandra-2, tasks.cassandra-3, tasks.cassandra-4, tasks.cassandra-5, tasks.cassandra-6, tasks.cassandra-7"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/cassandra.yaml"
        target: "/etc/cassandra/cassandra.yaml"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra

networks:
  cassandra:
    external:
      name: cassandraNet