version: '3.3'
services:
  cassandra-1:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n1
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-1
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - "~/etl-nosql/db/cassandra/var/lib/cassandra/3/1:/var/lib/cassandra"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    ports:
      - "7000:7000"
      - "9042:9042"
    networks:
      - cassandra

  cassandra-2:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n2
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-2
      CASSANDRA_SEEDS: "tasks.cassandra-1"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - "~/etl-nosql/db/cassandra/var/lib/cassandra/3/1:/var/lib/cassandra"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra
  cassandra-3:
    image: cassandra:latest
    deploy:
      placement:
        constraints:
          - node.labels.node==n3
    environment:
      CASSANDRA_LISTEN_ADDRESS: tasks.cassandra-3
      CASSANDRA_SEEDS: "tasks.cassandra-1, tasks.cassandra-2"
    volumes:
      - "~/etl-nosql/db/cassandra/tables_schema:/tables_schema"
      - "~/etl-nosql/db/table_data:/table_data"
      - "~/etl-nosql/db/cassandra/var/lib/cassandra/3/1:/var/lib/cassandra"
      - type: bind
        source: "~/etl-nosql/db/cassandra/etc/cassandra/jvm.options"
        target: "/etc/cassandra/jvm.options"
    depends_on:
      - "cassandra-1"
    ports:
      - 7000
      - 9042
    networks:
      - cassandra

networks:
  cassandra:
    external:
      name: cassandraNet