---

- hosts: cluster_node_manager
  tasks:
    - name: Manager - remove stack
      ansible.builtin.command: "docker stack rm {{db['docker_stack_name']}}"
      when: leave_cluster
      tags: tag_workers_leave_cluster

    - name: Manager - remove network
      ansible.builtin.command: "docker network rm {{db['network_name']}}"
      when: leave_cluster
      tags: tag_workers_leave_cluster


- hosts: cluster_node_workers
  tasks:
    - name: Workers - Leave cluster
      ansible.builtin.command: "docker swarm leave"
      when: leave_cluster
      tags: tag_workers_leave_cluster


- hosts: cluster_node_manager
  tasks:
    - name: Manager - Leave cluster
      ansible.builtin.command: "docker swarm leave --force"
      when: leave_cluster
      tags: tag_manager_leave_cluster


- hosts: cluster_node_workers:cluster_node_manager
  tasks:
    - name: Restore files from backup
      block:
        - name: Backup files
          ansible.builtin.copy:
            src: "{{ item.file_path }}/{{ item.file_name }}.backup"
            dest: "{{ item.file_path }}/{{ item.file_name }}"
          loop: "{{ change_files }}"
      when: restore_files
      tags: tag_restore_files


