---

- hosts: cluster_node_manager:cluster_node_workers
  tasks:
    - name: Reset repo
      ansible.builtin.command: "git -C etl-nosql/ reset --hard"
      with_items: "{{ make_dirs }}"

    - name: Pull repo
      ansible.builtin.command: "git -C etl-nosql/ pull"
      with_items: "{{ make_dirs }}"

    - name: Make directories
      ansible.builtin.command: "mkdir -p {{ item }}"
      with_items: "{{ make_dirs }}"
      tags: make_dirs

    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest:  "{{ item.dest }}"
      with_items: "{{ copy_files }}"
      tags: copy_files


