- hosts: cluster_node_manager
  tasks:
    - name: Create DB namespace
      block:
        - name: Get container ID
          ansible.builtin.command: "docker ps -q --filter 'name={{db['docker_stack_name']}}*' "
          register: container_id

        - name: DB create namespace
          ansible.builtin.command: "docker exec {{container_id.stdout}} cqlsh -f /tables_schema/keyspace"
      tags: tag_create_namespace
