- hosts: cluster_node_manager
  tasks:
    - name: Create schema
      block:
        - name: Get container ID 3
          ansible.builtin.command: "docker ps -q --filter name={{db['docker_stack_name']}}* "
          register: container_id

        - name: Drop tables
          ansible.builtin.command: "docker exec {{container_id.stdout}} cqlsh -e 'DROP TABLE {{namespace}}.{{item}};'"
          loop: "{{tables_schema}}"
          ignore_errors: True

        - name: Create schema
          ansible.builtin.command: "docker exec {{container_id.stdout}} cqlsh -f /tables_schema/{{item}}"
          loop: "{{tables_schema}}"
      tags: tag_load_data
