- hosts: cluster_node_manager
  tasks:
    - name: Create docker network
      ansible.builtin.command: "docker network create -d overlay {{ db['network_name'] }}"
      when: create_cluster_network
      tags:
        - tag_create_cluster
        - tag_create_cluster


- hosts: cluster_node_manager
  tasks:
    - name: Docker stack up
      ansible.builtin.command: "docker stack deploy -c {{docker_compose_file}} {{db['docker_stack_name']}}"
      tags: tag_docker_stack_deploy


    - name: Wait for first container and get container ID
      ansible.builtin.command: "docker ps -q --filter name={{db['docker_stack_name']}}* "
      register: container_id
      until: container_id.stdout != ""
      retries: 20
      delay: 5
      tags: tag_docker_stack_deploy

    - name: Wait for first container
      pause:
        seconds: 30

    - name: Wait for all nodes in cluster
      ansible.builtin.command: "docker exec {{container_id.stdout}} nodetool status"
      register: asd

    - name: Wait for all nodes in cluster
      ansible.builtin.command: "docker exec {{container_id.stdout}} nodetool status"
      register: cmd_res_wait
      until: "cmd_res_wait.stdout_lines | length == cluster_size + 5"
      retries: 10
      delay: 60
      tags: tag_docker_stack_deploy