---

- hosts: cluster_node_manager
  tasks:
    - name: Make directories
      ansible.builtin.command: "mkdir -p {{ data_generator.tables_dest }}/{{ item }}"
      with_items: "{{ data_generator.sizes }}"
      tags: make_dirs


- hosts: cluster_node_manager
  tasks:
    - name: Generate data
      block:
        - name: Generate data
          ansible.builtin.command: "{{ data_generator['gen_path']}}/dsdgen -DIR {{data_generator['tables_dest'] }}/{{ item.1 }} -SCALE {{ item.1 }} -TERMINATE {{ data_generator['terminate']}} -RNGSEED {{data_generator['rngseed'] }} -FORCE {{data_generator['force'] }} -DISTRIBUTIONS {{data_generator['distr'] }} -TABLE {{ item.0 }}"
          with_nested:
            - "{{ data_generator['sizes'] }}"
            - "{{ data_generator['tables'] }}"

      ignore_errors: true
      tags: tag_create_table_data

