- hosts: cluster_node_manager
  tasks:
    - name: Init docker swarm node manager
      block:
        - name: Init swarm
          ansible.builtin.command:  docker swarm init

        - name: Register swarm worker token
          ansible.builtin.command: docker swarm join-token -q worker
          register: cluster_token

      when: create_cluster
      tags: tag_create_cluster


- hosts: cluster_node_workers
  tasks:
    - name: Init docker swarm workers
      block:
        - name: Init swarm workers
          ansible.builtin.command:  "docker swarm join --token {{ hostvars[cluster['node_manager']]['cluster_token'].stdout }} {{cluster['node_manager']}}:2377"
      when: create_cluster
      tags: tag_create_cluster


- hosts: cluster_node_manager
  tasks:
    - name: Get nodes id, add labels
      block:
        - name: Get manager id
          ansible.builtin.command:  "docker node ls -q -f 'role=manager'"
          register: cluster_manager_id

        - name: Get worker id
          ansible.builtin.command:  "docker node ls -q -f 'role=worker'"
          register: cluster_worker_id

        - name: Add manager label
          ansible.builtin.command: "docker node update --label-add node=n1 {{ cluster_manager_id.stdout }}"

        - name: Add node labels
          ansible.builtin.command: "docker node update --label-add node=n{{ node_idx+2 }} {{ item }}"
          loop: "{{ cluster_worker_id.stdout_lines }}"
          loop_control:
            index_var: node_idx

      tags: tag_create_cluster


